spring.application.name=pedidos

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
spring.rabbitmq.dynamic=true

# datasource
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:pedidos
spring.datasource.username=sa
spring.datasource.password=sa


spring.rabbitmq.listener.simple.default-requeue-rejected=false

spring.output.ansi.enabled=ALWAYS
server.servlet.context-path=/api

# jpa
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false

# h2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Filas
rabbitmq.queue.producer.verificar-estoque=pedido.criado.verificar-estoque
rabbitmq.queue.producer.estoque-produtos=estoque.estoque-produtos

rabbitmq.queue.consumer.estoque-estoque-verificado=pedido.criado.estoque-verificado
rabbitmq.queue.consumer.estoque-produtos-lista=estoque.estoque-produtos-lista

rabbitmq.queue.consumer.estoque-estoque-verificado-dead-letter=pedido.criado.estoque-verificado-dead-letter
rabbitmq.queue.consumer.estoque-produtos-lista-dead-letter=estoque.estoque-produtos-lista-dead-letter

rabbitmq.queue.exchange-pedidos=pedido.exchange-direct

logging.level.org.springframework.amqp=DEBUG
logging.level.com.rabbitmq=DEBUG
